### ISSUE TITLE
Beating the Daily DownScale Limitation?

### ISSUE THREAD

**Issue by ninjada** [sebdah/dynamic-dynamodb#306]
have been tweaking dynamic-dynamodb for a few weeks now, but it's got me beat trying to work around amazon's max 4 downscales within a 24hour period.

one of my table experiences sits at around 500 writes but has a regular burst to 2000-2500 for ~30minutes every 3 to 4 hours. so this may happen 6+ times in a 24hour period, 

here's an image.

![](http://ninjada.com/dynamo.png)

I'm having a bit of trouble fitting this into the 4 downscales per 24hour period limitation. I've tried coming up with a config so that it only downscales every other spike, but haven't had much luck. I think there'd need to be some other config options to achieve that.

any config advice?

**Comment by Poratsh** [comment]
+1

**Comment by usrenmae** [comment]
@ninjada As it's 6+ times a day for your table, and it's an AWS limit which is applied here, you cannot even theoretically overcome it with your dynamic-dynamodb configuration. You may want to request an increase of the DynamoDB limits via AWS Support. They are usually very open to increase some of the limits on per-account basis.

Another solution to downscale on every other spike is to use `num-*-checks-before-scale-down: N` and calculate `N` based on your polling and spiking periods. But this is of course half measure because it hardly depends on those period numbers, and won't adjust dynamically.

**Comment by equake** [comment]
@ninjada You can ask AWS to increase your downscaling limits. Just open an support ticket. We've done that. :)

**Comment by ninjada** [comment]
@equake oh man, thanks! stupidly assumed aws was enforcing a hard limit, having seen the problem raised a few times..such a simple solution... doy.
